'use client';
import Head from "next/head";
import Image from "next/image";
import React from 'react';
import axios from 'axios';
import Button from '@mui/material/Button';

export default function Home() {
  const handleSubscription = async (e) => {
    e.preventDefault();
    const { data } = await axios.post('/api/route',
    {
      priceId: "price_1OHWdTKwZOLBQ6VV36IQAx6L"
    },
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
    );
    window.location.assign(data)
  }
  
  return (
    <div>
      <Head>
        <title>Physical NFTs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Buy my physical NFTs</h1>
        <div style={{ display: 'flex', gap: '50px'}}>
          <div>
            <Image
              src="/1.jpg"
              alt="NFT"
              width={150}
              height={150}
            />
            <h3>Very expensive art piece 1</h3>
            {/* 确保你已经定义了checkout函数或者你已经导入了checkout */}
            <Button variant="contained" color="primary" onClick={handleSubscription}>BUY!</Button>
          </div>
          <div>
            <Image
              src="/2.jpg"
              alt="NFT"
              width={150}
              height={150}
            />
            <h3>Very expensive art piece 2</h3>
            {/* 你可能还想添加购买第二件艺术品的功能 */}
          </div>
        </div>
      </main>
    </div>
  )
}
